---
search_languages:
    sv:
        link: Svenska
        placeholder: Sök på Wikipedia
    ar:
        link: العربية
        placeholder: ابحث في ويكيبيديا
        direction: rtl
    bs:
        link: Bosanski
        placeholder: Pretraži Wikipediju
    da:
        link: Dansk
        placeholder: Søg på Wikipedia
    de:
        link: Deutsch
        placeholder: Wikipedia durchsuchen
    en:
        link: English
        placeholder: Search Wikipedia
    es:
        link: Español
        placeholder: Buscar en Wikipedia
    fa:
        link: فارسی
        placeholder: جستجو در ویکی‌پدیا
        direction: rtl
    fi:
        link: Suomi
        placeholder: Hae Wikipediasta
    ku:
        link: Kurdî/كوردی
        placeholder: Li ser Wîkîpediya bigere
    "no":
        link: ‪Norsk
        placeholder: Søk i Wikipedia
    se:
        link: Sámegiella
        placeholder: Oza Wikipedia:s
    sr:
        link: Српски/Srpski
        placeholder: Претражите Википедију
footer:
    - block_type: logo
      image: wikimedia-logo.svg
      url: https://wikimedia.se
      alt: Wikimedia Sverige
    - block_type: links
      header: Wikimedia Sverige
      links:
          Om oss: https://wikimedia.se/om-oss/
          Integritetspolicy: https://wikimedia.se/integritetspolicy
    - block_type: links
      header: Engagera dig
      links:
          Bli medlem: http://nymedlem.wikimedia.se/
          Donera: https://wikimedia.se/donera/
    - block_type: logo
      image: 90-konto-logo.png
      url: https://www.insamlingskontroll.se/90-konto-organisationer/
      alt: 90-konto, svensk insamlingskontroll
...
